---
abstract: "Check the compiler's availability"
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-CheckCompiler
no_index:
  directory:
    - inc
provides:
  Devel::AssertC99:
    file: lib/Devel/AssertC99.pm
    version: 0
  Devel::CheckCompiler:
    file: lib/Devel/CheckCompiler.pm
    version: 0.02
requires:
  Exporter: 0
  ExtUtils::CBuilder: 0
  File::Temp: 0
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
